### ISSUE TITLE
Login is buggy on Heroku server

### ISSUE THREAD

**Issue by zakgreene** [bastianallgeier/kirbycms-panel#82]
When I try to use the panel on Heroku, the login works sporadically. Often when I enter my credentials properly, the login screen reloads (without the red button indicating the credentials are wrong). Sometimes it lets me in, but then every time I open a new page in the panel the login screen reappears. This only happens on Heroku, not locally. I've not encountered it on other live instances of Kirby uploaded with FTP (instead of Git).

**Comment by bungle** [comment]
I'm also having this issue with Nginx.

**Comment by bungle** [comment]
I have now traced this to a problem with CSRF.

**Comment by zakgreene** [comment]
I realize now, after a bit more experience with Heroku, that a CMS like Kirby (the panel, at least) doesn't work with Heroku because Heroku's file system is ephemeral — files can only be written temporarily, and must use a `/tmp` directory. When I posted this issue, I'd be able to successfully save a change, but it would always reset to the state I last pushed via Git. Would be curious to hear if someone has been successful with it, though.
