### ISSUE TITLE
Over 21 "items" in Kirby panel

### ISSUE THREAD

**Issue by hyperperforator** [bastianallgeier/kirbycms-panel#94]
Hi,

I am running a blog on Kirby. Now that I've got over 21 "items" posted to my blog, every time I set one to be public, it shows it as item number 21. All of them are now item 21 after that. is this a bug? What have I done wrong?

**Comment by bastianallgeier** [comment]
Is this happening with Kirby 2?

**Comment by hyperperforator** [comment]
Yes! 
![screen shot 2015-01-12 at 9 46 36 am](https://cloud.githubusercontent.com/assets/3075582/5696750/ed9b84dc-9a3f-11e4-9a20-c247e8049b8b.png)

**Comment by bastianallgeier** [comment]
Looks extremely weird. Could you please send me an email: bastian@getkirby.com It would be easier to check out your installation directly.
