### ISSUE TITLE
Panel Not Saving Changes

### ISSUE THREAD

**Issue by peterbinks** [bastianallgeier/kirbycms-panel#95]
I try to edit the contents of a page in the panel, and on save it erases the changes and reverts back. 

I'm honestly not entirely sure what's causing this problem, but it started after i upgraded to Kirby 2.0.6.

**Comment by lulezi** [comment]
The repository for Kirby v2 is at https://github.com/getkirby/kirby (and the panel is at https://github.com/getkirby/panel).

**Comment by peterbinks** [comment]
So I figured out what was going on. With the multiple language update, kirby created a default.txt and default.en.txt file in each pages directory. While changes were being saved to dault.en.txt, kirby uses default.txt to serve the page and to display in the panel. So just getting rid of the .txt file solved this. Though Kirby could probably by default either replace, or append .en.txt to the page file.
